apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.name }}-svc
  labels:
    slack-app: {{ .Values.chart.name }}-svc

spec:
  ports:
  - port: 5000
    targetPort: 5000  # temp for testing, change to image port
    name: http
    protocol: TCP
  selector:
    slack-app: {{ .Values.chart.name }}-svc
  sessionAffinity: None
  type: ClusterIP