apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.chart.name }}-svc-monitor
  labels:
    slack-app: {{ .Values.chart.name }}-svc
spec:
  selector:
    matchLabels:
      slack-app: {{ .Values.chart.name }}-svc
  endpoints:
  - port: http