project: default
source:
  repoURL: 'https://github.com/Christian-Bull/slack-twitch-slash.git'
  path: charts/slack-twitch-slash
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: image.tag
        value: main-latest
destination:
  server: 'https://kubernetes.default.svc'
  namespace: cbull
syncPolicy:
  automated: {}
