apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chart.name }}
  labels:
    app: {{ .Values.chart.name }}
    service: {{ .Values.chart.name }}-svc
spec:
  replicas: {{ .Values.image.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.chart.name }}-svc
  template:
    metadata:
      labels:
        service: {{ .Values.chart.name }}-svc
        role: {{ .Values.chart.name }}
    spec:
      serviceAccountName: {{ .Values.chart.name }}
      containers:
        - name: {{ .Values.chart.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.chart.name }}-cm
