apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.chart.name }}
  labels:
    slack-app: {{ .Values.chart.name }}-svc
spec:
  ingressClassName: external
  rules:
    - host: {{ .Values.global.ingress_domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ .Values.chart.name }}-svc
              servicePort: 5000