apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.chart.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/listen-ports:  '[{"HTTP": 80}]'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    nginx.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - host: {{ .Values.global.ingress_domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.chart.name }}-svc
                port:
                  number: 443