name: deploy

on:
  workflow_run:
    workflows: ["buildAndPush"]
    branches: [main]
    types:
      - completed

jobs:

  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: set env vars
        run: |
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: update deployment spec
        run: |
          export SED_REPLACE_TAG=${{ env.GITHUB_REF_NAME }}-${{ env.SHA }}
          sed -i 's|^\(\s*tag\s*:\s*\).*|\1'"$SED_REPLACE_TAG"'|' charts/slack-twitch-slash/values.yaml

      - name: Create Pull Request
        uses: EndBug/add-and-commit@v7
        with:
          new_branch: pipeline-test-01